/**
 * @file mod/LuaBindings_ScanCode.cpp
 * @author JagYayu
 * @brief
 * @version 1.0
 * @date 2025
 *
 * @copyright Copyright (c) 2025 JagYayu. Licensed under MIT License.
 *
 */

#include "mod/LuaBindings.hpp"

#include "system/ScanCode.hpp"

using namespace tudov;

#define TE_ENUM(Class, ...) lua.new_enum<Class>(#Class, __VA_ARGS__)

void LuaBindings::InstallScanCode(sol::state &lua, Context &context) noexcept
{
	TE_ENUM(EScanCode,
	        {
	            {"A", EScanCode::A},
	            {"B", EScanCode::B},
	            {"C", EScanCode::C},
	            {"D", EScanCode::D},
	            {"E", EScanCode::E},
	            {"F", EScanCode::F},
	            {"G", EScanCode::G},
	            {"H", EScanCode::H},
	            {"I", EScanCode::I},
	            {"J", EScanCode::J},
	            {"K", EScanCode::K},
	            {"L", EScanCode::L},
	            {"M", EScanCode::M},
	            {"N", EScanCode::N},
	            {"O", EScanCode::O},
	            {"P", EScanCode::P},
	            {"Q", EScanCode::Q},
	            {"R", EScanCode::R},
	            {"S", EScanCode::S},
	            {"T", EScanCode::T},
	            {"U", EScanCode::U},
	            {"V", EScanCode::V},
	            {"W", EScanCode::W},
	            {"X", EScanCode::X},
	            {"Y", EScanCode::Y},
	            {"Z", EScanCode::Z},
	            {"Num1", EScanCode::Num1},
	            {"Num2", EScanCode::Num2},
	            {"Num3", EScanCode::Num3},
	            {"Num4", EScanCode::Num4},
	            {"Num5", EScanCode::Num5},
	            {"Num6", EScanCode::Num6},
	            {"Num7", EScanCode::Num7},
	            {"Num8", EScanCode::Num8},
	            {"Num9", EScanCode::Num9},
	            {"Num0", EScanCode::Num0},
	            {"Return", EScanCode::Return},
	            {"Escape", EScanCode::Escape},
	            {"Backspace", EScanCode::Backspace},
	            {"Tab", EScanCode::Tab},
	            {"Space", EScanCode::Space},
	            {"Minus", EScanCode::Minus},
	            {"Equals", EScanCode::Equals},
	            {"LeftBracket", EScanCode::LeftBracket},
	            {"RightBracket", EScanCode::RightBracket},
	            {"Backslash", EScanCode::Backslash},
	            {"Semicolon", EScanCode::Semicolon},
	            {"Apostrophe", EScanCode::Apostrophe},
	            {"Grave", EScanCode::Grave},
	            {"Comma", EScanCode::Comma},
	            {"Period", EScanCode::Period},
	            {"Slash", EScanCode::Slash},
	            {"CapsLock", EScanCode::CapsLock},
	            {"F1", EScanCode::F1},
	            {"F2", EScanCode::F2},
	            {"F3", EScanCode::F3},
	            {"F4", EScanCode::F4},
	            {"F5", EScanCode::F5},
	            {"F6", EScanCode::F6},
	            {"F7", EScanCode::F7},
	            {"F8", EScanCode::F8},
	            {"F9", EScanCode::F9},
	            {"F10", EScanCode::F10},
	            {"F11", EScanCode::F11},
	            {"F12", EScanCode::F12},
	            {"F13", EScanCode::F13},
	            {"F14", EScanCode::F14},
	            {"F15", EScanCode::F15},
	            {"F16", EScanCode::F16},
	            {"F17", EScanCode::F17},
	            {"F18", EScanCode::F18},
	            {"F19", EScanCode::F19},
	            {"F20", EScanCode::F20},
	            {"F21", EScanCode::F21},
	            {"F22", EScanCode::F22},
	            {"F23", EScanCode::F23},
	            {"F24", EScanCode::F24},
	            {"PrintScreen", EScanCode::PrintScreen},
	            {"ScrollLock", EScanCode::ScrollLock},
	            {"Pause", EScanCode::Pause},
	            {"Insert", EScanCode::Insert},
	            {"Home", EScanCode::Home},
	            {"PageUp", EScanCode::PageUp},
	            {"Delete", EScanCode::Delete},
	            {"End", EScanCode::End},
	            {"PageDown", EScanCode::PageDown},
	            {"Right", EScanCode::Right},
	            {"Left", EScanCode::Left},
	            {"Down", EScanCode::Down},
	            {"Up", EScanCode::Up},
	            {"NumLock", EScanCode::NumLock},
	            {"KeypadDivide", EScanCode::KeypadDivide},
	            {"KeypadMultiply", EScanCode::KeypadMultiply},
	            {"KeypadMinus", EScanCode::KeypadMinus},
	            {"KeypadPlus", EScanCode::KeypadPlus},
	            {"KeypadEnter", EScanCode::KeypadEnter},
	            {"Keypad1", EScanCode::Keypad1},
	            {"Keypad2", EScanCode::Keypad2},
	            {"Keypad3", EScanCode::Keypad3},
	            {"Keypad4", EScanCode::Keypad4},
	            {"Keypad5", EScanCode::Keypad5},
	            {"Keypad6", EScanCode::Keypad6},
	            {"Keypad7", EScanCode::Keypad7},
	            {"Keypad8", EScanCode::Keypad8},
	            {"Keypad9", EScanCode::Keypad9},
	            {"Keypad0", EScanCode::Keypad0},
	            {"KeypadPeriod", EScanCode::KeypadPeriod},
	            {"KeypadEquals", EScanCode::KeypadEquals},
	            {"KeypadComma", EScanCode::KeypadComma},
	            {"Keypad00", EScanCode::Keypad00},
	            {"Keypad000", EScanCode::Keypad000},
	            {"KeypadLeftParen", EScanCode::KeypadLeftParen},
	            {"KeypadRightParen", EScanCode::KeypadRightParen},
	            {"KeypadLeftBrace", EScanCode::KeypadLeftBrace},
	            {"KeypadRightBrace", EScanCode::KeypadRightBrace},
	            {"KeypadTab", EScanCode::KeypadTab},
	            {"KeypadBackspace", EScanCode::KeypadBackspace},
	            {"KeypadA", EScanCode::KeypadA},
	            {"KeypadB", EScanCode::KeypadB},
	            {"KeypadC", EScanCode::KeypadC},
	            {"KeypadD", EScanCode::KeypadD},
	            {"KeypadE", EScanCode::KeypadE},
	            {"KeypadF", EScanCode::KeypadF},
	            {"KeypadXor", EScanCode::KeypadXor},
	            {"KeypadPower", EScanCode::KeypadPower},
	            {"KeypadPercent", EScanCode::KeypadPercent},
	            {"KeypadLess", EScanCode::KeypadLess},
	            {"KeypadGreater", EScanCode::KeypadGreater},
	            {"KeypadAmpersand", EScanCode::KeypadAmpersand},
	            {"KeypadDoubleAmp", EScanCode::KeypadDoubleAmp},
	            {"KeypadVerticalBar", EScanCode::KeypadVerticalBar},
	            {"KeypadDoubleVerticalBar", EScanCode::KeypadDoubleVerticalBar},
	            {"KeypadColon", EScanCode::KeypadColon},
	            {"KeypadHash", EScanCode::KeypadHash},
	            {"KeypadSpace", EScanCode::KeypadSpace},
	            {"KeypadAt", EScanCode::KeypadAt},
	            {"KeypadExclam", EScanCode::KeypadExclam},
	            {"KeypadMemStore", EScanCode::KeypadMemStore},
	            {"KeypadMemRecall", EScanCode::KeypadMemRecall},
	            {"KeypadMemClear", EScanCode::KeypadMemClear},
	            {"KeypadMemAdd", EScanCode::KeypadMemAdd},
	            {"KeypadMemSubtract", EScanCode::KeypadMemSubtract},
	            {"KeypadMemMultiply", EScanCode::KeypadMemMultiply},
	            {"KeypadMemDivide", EScanCode::KeypadMemDivide},
	            {"KeypadPlusMinus", EScanCode::KeypadPlusMinus},
	            {"KeypadClear", EScanCode::KeypadClear},
	            {"KeypadClearEntry", EScanCode::KeypadClearEntry},
	            {"KeypadBinary", EScanCode::KeypadBinary},
	            {"KeypadOctal", EScanCode::KeypadOctal},
	            {"KeypadDecimal", EScanCode::KeypadDecimal},
	            {"KeypadHexadecimal", EScanCode::KeypadHexadecimal},
	            {"LeftControl", EScanCode::LeftControl},
	            {"LeftShift", EScanCode::LeftShift},
	            {"LeftAlt", EScanCode::LeftAlt},
	            {"LeftGui", EScanCode::LeftGui},
	            {"RightControl", EScanCode::RightControl},
	            {"RightShift", EScanCode::RightShift},
	            {"RightAlt", EScanCode::RightAlt},
	            {"RightGui", EScanCode::RightGui},
	            {"International1", EScanCode::International1},
	            {"International2", EScanCode::International2},
	            {"International3", EScanCode::International3},
	            {"International4", EScanCode::International4},
	            {"International5", EScanCode::International5},
	            {"International6", EScanCode::International6},
	            {"International7", EScanCode::International7},
	            {"International8", EScanCode::International8},
	            {"International9", EScanCode::International9},
	            {"Lang1", EScanCode::Lang1},
	            {"Lang2", EScanCode::Lang2},
	            {"Lang3", EScanCode::Lang3},
	            {"Lang4", EScanCode::Lang4},
	            {"Lang5", EScanCode::Lang5},
	            {"Lang6", EScanCode::Lang6},
	            {"Lang7", EScanCode::Lang7},
	            {"Lang8", EScanCode::Lang8},
	            {"Lang9", EScanCode::Lang9},
	            {"MediaNext", EScanCode::MediaNext},
	            {"MediaPrev", EScanCode::MediaPrev},
	            {"MediaStop", EScanCode::MediaStop},
	            {"MediaPlay", EScanCode::MediaPlay},
	            {"MediaMute", EScanCode::MediaMute},
	            {"MediaSelect", EScanCode::MediaSelect},
	            {"AcSearch", EScanCode::AcSearch},
	            {"AcHome", EScanCode::AcHome},
	            {"AcBack", EScanCode::AcBack},
	            {"AcForward", EScanCode::AcForward},
	            {"AcStop", EScanCode::AcStop},
	            {"AcRefresh", EScanCode::AcRefresh},
	            {"AcBookmarks", EScanCode::AcBookmarks},
	        });
}
